# Generated by Django 4.2.10 on 2024-02-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slokaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='viewedit',
            field=models.BooleanField(default=False),
        ),
    ]
